### ISSUE TITLE
Request: Commit drum .wav files to assets submodule

### ISSUE THREAD

**Issue by dlancea** [gridsound/daw#62]
Hello,

I'm working on a self-hosted version of GridSound. One issue I have is that the drum .wav files in the samples directory are missing from the assets repo. Would it be possible to add those in for easier building?

Thanks!

**Comment by dlancea** [comment]
Also, generally speaking, is a self-hosted version of GridSound something this project would be interested in? Or is it primarily only intended to be hosted on gridsound.com?

I feel like with a few tweaks to make some things more portable this could take off as a self-hosted application.

**Comment by dlancea** [comment]
Also, I can provide a PR for this and other changes, if desired.

**Comment by mr21** [comment]
Hello :)

Thx for your interest in the project, you were right to ask, having the app somewhere else than inside a tab is not my priority.
The fact that Chrome offers the possibility to "install" a website (with a shortcut on the desktop etc.) continues to decrease the priority on this point. But it would be cool to see your proposition anyway, what would you use to self-host the app?

About the samples, they are not here just because i was not confident about pushing WAVE files on GitHub..
But they are here:
https://gridsound.com/assets/samples/kick-00.wav
https://gridsound.com/assets/samples/clap-00.wav
https://gridsound.com/assets/samples/snare-00.wav
https://gridsound.com/assets/samples/hat-00.wav
https://gridsound.com/assets/samples/hat-open-00.wav

**Comment by dlancea** [comment]
What I meant was self-hosted on a personal server in people's homes. It's a fairly popular hobby. Here's a list of of other apps that are intended or often used for self-hosting: https://github.com/awesome-selfhosted/awesome-selfhosted

Most of the code base seems well suited for this, since the server requirements are low. The changes I would propose are ones that make the code more portable. For instance these .wav files are referenced in the code as part of the default project setup, but they aren't available in repository. Also some other things aren't portable like the [API client code explicitly sets the URL to the registered GridSound Domain](https://github.com/gridsound/gs-api-client/blob/master/gsapiClient.js#L4).

I think it would be pretty simple to allow the app to live both on GridSound.com (unobtrusively to you) and be available for people to setup and run on their own servers.

**Comment by mr21** [comment]
I understand what you meant but for the moment the priority is to work on the gridsound.com, we will the rest after
